# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20170827_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeentertaiment',
            options={'verbose_name': 'Развлечение', 'verbose_name_plural': 'Развлечения'},
        ),
    ]
