# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20170827_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeentertaiment',
            name='top',
            field=models.BooleanField(default=True, verbose_name='Топ'),
            preserve_default=False,
        ),
    ]
