# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_placeorder_placesearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='category_image', verbose_name='Изображение')),
                ('category_choice', models.CharField(choices=[('Search', 'Найти'), ('Order', 'Заказать'), ('Entertaiment', 'Развлечения')], default='Search', max_length=100, verbose_name='Раздел')),
            ],
            options={
                'verbose_name_plural': 'Категории заказать',
                'verbose_name': 'Категория заказать',
            },
        ),
        migrations.CreateModel(
            name='CategorySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='category_image', verbose_name='Изображение')),
                ('category_choice', models.CharField(choices=[('Search', 'Найти'), ('Order', 'Заказать'), ('Entertaiment', 'Развлечения')], default='Search', max_length=100, verbose_name='Раздел')),
            ],
            options={
                'verbose_name_plural': 'Категории поиска',
                'verbose_name': 'Категория поиска',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryEntertaiment',
        ),
        migrations.AlterModelOptions(
            name='categoryentertaiment',
            options={'verbose_name': 'Категория развлечений', 'verbose_name_plural': 'Категории развлечений'},
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.CategoryOrder', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='placesearch',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.CategorySearch', verbose_name='Категория'),
        ),
    ]
