# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20171013_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryentertaiment',
            name='category_choice',
        ),
        migrations.RemoveField(
            model_name='categoryorder',
            name='category_choice',
        ),
        migrations.RemoveField(
            model_name='categorysearch',
            name='category_choice',
        ),
        migrations.RemoveField(
            model_name='categorysearch',
            name='image',
        ),
    ]
