# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20171013_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeentertaiment',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=(100.0, -20.0), max_length=63),
        ),
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата'),
        ),
    ]
