# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20171111_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='koordinates',
            name='length',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koordinates',
            name='width',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
