# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20171111_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='koordinates',
            name='city',
            field=models.CharField(default='48.737512197810915,397.5847434997558', max_length=1000, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='placeentertaiment',
            name='city',
            field=models.CharField(default='48.737512197810915,397.5847434997558', max_length=1000, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='placesearch',
            name='city',
            field=models.CharField(default='48.737512197810915,397.5847434997558', max_length=1000, verbose_name='Координаты'),
        ),
    ]
