# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20171111_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeentertaiment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='placesearch',
            name='city',
        ),
    ]
